version: '3'

services:

  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    environment:
      - 2AXONSERVER_HOSTNAME=axonserver

  command-service:
    build:
      context: .
      dockerfile: ./command-service/Dockerfile
    ports:
      - 8081:8080

  query-service:
    build:
      context: .
      dockerfile: ./query-service/Dockerfile
    ports:
      - 8082:8080
