apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: axonserver
    labels:
      app: axonserver
  spec:
    serviceName: axonserver
    replicas: 1
    selector:
      matchLabels:
        app: axonserver
    template:
      metadata:
        labels:
          app: axonserver
      spec:
        containers:
          - name: axonserver
            image: axoniq/axonserver
            env:
            - name: AXONSERVER_HOSTNAME
             value: axonserver
            imagePullPolicy: Always
            ports:
            - name: grpc
              containerPort: 8124
              protocol: TCP
            - name: gui
              containerPort: 8024
              protocol: TCP
