apiVersion: 
kind: Pod
metadata:
  name: command-service
  labels:
    name: peanuts
    app: axonserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: axonserver
    spec:
      containers:
      - image: celcin/command-svc
        name: command-service
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: command-service
  labels:
    name: peanuts
    app: axonserver
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8080
  selector:
    labels:
      app: axonserver
