apiVersion: extensions/v1beta1
kind: Pod
metadata:
  name: command-service
  labels:
    name: peanuts
    app: axonserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: command-service
    spec:
      containers:
      - image: celcin/command-svc
        name: command-service
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: command-service
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8080
  selector:
    io.kompose.service: command-service
status:
  loadBalancer: {}
