apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: query-service
  name: query-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: query-service
    spec:
      containers:
      - image: celcin/query-svc
        name: query-service
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
