apiVersion: v1b
kind: Pod
metadata:
  name: query-service
  labels:
  name: peanuts
  app: axonserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: axonserver
    spec:
      containers:
      - image: celcin/query-svc
        name: query-service
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: query-service
  labels:
    name: peanuts
    app: axonserver
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8080
  selector:
    labels:
      app: axonserver
status:
  loadBalancer: {}

